# SPDX-FileCopyrightText: 2024-2026 Temps Contributors
# SPDX-License-Identifier: MIT OR Apache-2.0

[package]
name = "temps-screenshots"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
axum = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
utoipa = { workspace = true }

# Screenshot dependencies
headless_chrome = {version ="1.0.18", features = ["fetch", "offline"] }
reqwest = { workspace = true }
url = { workspace = true }
base64 = "0.23"
bytes = { workspace = true }

temps-config = { path = "../temps-config" }
temps-core = { path = "../temps-core" }
temps-file-store = { path = "../temps-file-store" }

[dev-dependencies]
tokio-test = "0.4"
mockito = "1.5"
tempfile = "3.8"
temps-database = { path = "../temps-database" }
sea-orm = { workspace = true }
