# SPDX-FileCopyrightText: 2024-2026 Temps Contributors
# SPDX-License-Identifier: MIT OR Apache-2.0

[package]
name = "temps-geo"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
anyhow = "1.0"
arc-swap = "1.7"
axum = { workspace = true }
chrono = { version = "0.4", features = ["serde"] }
flate2 = { workspace = true }
log = "0.4"
maxminddb = { version = "0.32.0", features = ["mmap"] }
moka = { version = "0.12", features = ["future"] }
rand = { workspace = true }
reqwest = { workspace = true }
sea-orm = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = { workspace = true }
tar = { workspace = true }
thiserror = { workspace = true }
temps-config = { path = "../temps-config" }
temps-core = { path = "../temps-core" }
temps-database = { path = "../temps-database" }
temps-entities = { path = "../temps-entities" }
temps-auth = { path = "../temps-auth" }
url = { workspace = true }
utoipa = "5.1"
tracing = { workspace = true }
tokio = { version = "1.0", features = ["time", "rt", "fs"] }
tempfile = { workspace = true }

[dev-dependencies]
tokio = { version = "1.0", features = ["full"] }
