# SPDX-FileCopyrightText: 2024-2026 Temps Contributors
# SPDX-License-Identifier: MIT OR Apache-2.0

[package]
name = "temps-auth"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
temps-core = { path = "../temps-core" }
temps-entities = { path = "../temps-entities" }
temps-database = { path = "../temps-database" }
axum = { workspace = true }
axum-macros = { workspace = true }
tower = { workspace = true }
tower-cookies = { workspace = true }
cookie = { workspace = true }
argon2 = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
utoipa = { workspace = true }
chrono = { workspace = true }
sea-orm = { workspace = true }
log = { workspace = true }
anyhow = { workspace = true }
rand = { workspace = true }
uuid = { workspace = true }
totp-rs = { workspace = true }
base32 = "0.5.1"
sha2 = { workspace = true }
hex = { workspace = true }
qrcode = "0.14.1"
image = "0.25.6"
base64 = { workspace = true }
urlencoding = { workspace = true }
tracing = { workspace = true }
openidconnect = { workspace = true }
reqwest = { workspace = true }

[dev-dependencies]
temps-migrations = { path = "../temps-migrations" }
tokio-test = "0.4"
walkdir = { workspace = true }
