# SPDX-FileCopyrightText: 2024-2026 Temps Contributors
# SPDX-License-Identifier: MIT OR Apache-2.0

[package]
name = "temps-notifications"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
temps-auth = { path = "../temps-auth" }
temps-core = { path = "../temps-core" }
temps-database = { path = "../temps-database" }
temps-entities = { path = "../temps-entities" }
temps-cloud = { path = "../temps-cloud" }
temps-cloud-protocol = { path = "../temps-cloud-protocol" }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sea-orm = { workspace = true }
async-trait = { workspace = true }
log = { workspace = true }
anyhow = { workspace = true }
lettre = { workspace = true }
futures-util = { workspace = true }
reqwest = { workspace = true }
chrono = { workspace = true }
utoipa = { workspace = true }
uuid = { workspace = true }
axum = { workspace = true }
axum-macros = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tokio-test = "0.4"
testcontainers = { workspace = true }
tower = { version = "0.5", features = ["util"] }
wiremock = "0.6"
sea-orm-migration = { workspace = true }
temps-migrations = { path = "../temps-migrations" }
