# SPDX-FileCopyrightText: 2024-2026 Temps Contributors
# SPDX-License-Identifier: MIT OR Apache-2.0

[package]
name = "temps-projects"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true

[dev-dependencies]
temps-migrations = { path = "../temps-migrations" }
bollard = { workspace = true }

[dependencies]
temps-auth = { path = "../temps-auth" }
temps-config = { path = "../temps-config" }
temps-core = { path = "../temps-core" }
temps-database = { path = "../temps-database" }
temps-entities = { path = "../temps-entities" }
temps-environments = { path = "../temps-environments" }
temps-git = { path = "../temps-git" }
temps-queue = { path = "../temps-queue" }
temps-providers = { path = "../temps-providers" }
temps-presets = { path = "../temps-presets", features = ["openapi"] }
serde = { workspace = true }
tokio = { workspace = true }
log = { workspace = true }
tracing = { workspace = true }
sea-orm = { workspace = true }
sha2 = { workspace = true }
anyhow = { workspace = true }
utoipa = { workspace = true }
futures = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
axum = { workspace = true }
axum-macros = { workspace = true }
flate2 = { workspace = true }
http = { workspace = true }
futures-util = { workspace = true }
base64 = { workspace = true }
hex = { workspace = true }
rand = { workspace = true }
slug = { workspace = true }
tempfile = { workspace = true }
url = { workspace = true }
zip = { workspace = true }
