# SPDX-FileCopyrightText: 2024-2026 Temps Contributors
# SPDX-License-Identifier: MIT OR Apache-2.0

[package]
name = "temps-infra"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
temps-config = { path = "../temps-config" }
# Use workspace dependencies
tokio = { workspace = true }
axum = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
utoipa = { workspace = true }
bollard = { workspace = true }
reqwest = { workspace = true }
log = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }

# Crate-specific dependencies
if-addrs = "0.15"
parking_lot = "0.12"
hickory-resolver = "0.26"

# Plugin system dependencies
temps-core = { path = "../temps-core" }
temps-auth = { path = "../temps-auth" }
tracing = { workspace = true }

[dev-dependencies]
sea-orm = { workspace = true }
tokio-test = "0.4"
env_logger = "0.11"
tower = { workspace = true }
chrono = { workspace = true }
temps-entities = { path = "../temps-entities" }
