# SPDX-FileCopyrightText: 2024-2026 Temps Contributors
# SPDX-License-Identifier: MIT OR Apache-2.0

[package]
name = "temps-static-files"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
axum = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
utoipa = { workspace = true }

temps-config = { path = "../temps-config" }
temps-core = { path = "../temps-core" }
temps-auth = { path = "../temps-auth" }
temps-file-store = { path = "../temps-file-store" }
