# SPDX-FileCopyrightText: 2024-2026 Temps Contributors
# SPDX-License-Identifier: MIT OR Apache-2.0

[package]
name = "temps-status-page"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
temps-auth = { path = "../temps-auth" }
temps-config = { path = "../temps-config" }
temps-core = { path = "../temps-core" }
temps-database = { path = "../temps-database" }
temps-entities = { path = "../temps-entities" }
temps-projects = { path = "../temps-projects" }
serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
sea-orm = { workspace = true }
anyhow = { workspace = true }
utoipa = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
axum = { workspace = true }
axum-macros = { workspace = true }
http = { workspace = true }
url = { workspace = true }
reqwest = { workspace = true }
futures = { workspace = true }

[dev-dependencies]
temps-migrations = { path = "../temps-migrations" }
tokio-test = "0.4"
wiremock = "0.6"
hex = { workspace = true }
async-trait = { workspace = true }
